# Rust formatting configuration
# Using only stable features for CI compatibility

edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
max_width = 100

# Imports
reorder_imports = true
reorder_modules = true

# Code style
use_field_init_shorthand = true
use_try_shorthand = true

# Consistency
match_block_trailing_comma = true