# Rust formatting configuration
# Matches pmat quality standards

edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
max_width = 100

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Code style
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Functions
fn_params_layout = "Tall"
fn_single_line = false

# Structs and enums
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
trailing_semicolon = true
trailing_comma = "Vertical"

# Consistency
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0