//! OAuth authentication handlers for browser-based PKCE flow.
//!
//! These endpoints support the browser-side OAuth popup flow:
//! - `/api/auth/token-exchange`: Exchanges authorization code for access token
//! - `/api/auth/callback`: Serves the popup callback page
//! - `/api/auth/status`: Returns current authentication state

use axum::{extract::State, http::StatusCode, response::Html, Json};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

use crate::server::AppState;

/// Request body for the token exchange endpoint.
#[derive(Debug, Deserialize)]
pub struct TokenExchangeRequest {
    /// Authorization code from the OAuth callback.
    pub code: String,
    /// PKCE code verifier (generated by the browser).
    pub code_verifier: String,
}

/// Response from the token exchange endpoint.
#[derive(Debug, Serialize)]
pub struct TokenExchangeResponse {
    /// Whether the token exchange succeeded.
    pub success: bool,
    /// Error message if the exchange failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Exchange an OAuth authorization code for an access token.
///
/// The browser sends the authorization code and PKCE code_verifier.
/// This endpoint POSTs to the OAuth provider's token endpoint
/// (server-side to avoid CORS), then updates the proxy's auth header.
pub async fn token_exchange(
    State(state): State<Arc<AppState>>,
    Json(req): Json<TokenExchangeRequest>,
) -> Result<Json<TokenExchangeResponse>, (StatusCode, String)> {
    let oauth = state
        .config
        .oauth_config
        .as_ref()
        .ok_or((StatusCode::BAD_REQUEST, "OAuth not configured".to_string()))?;

    let redirect_uri = format!("http://localhost:{}/api/auth/callback", state.config.port);

    let resp: reqwest::Response = state
        .proxy
        .http_client()
        .post(&oauth.token_endpoint)
        .form(&[
            ("grant_type", "authorization_code"),
            ("code", req.code.as_str()),
            ("redirect_uri", redirect_uri.as_str()),
            ("client_id", oauth.client_id.as_str()),
            ("code_verifier", req.code_verifier.as_str()),
        ])
        .send()
        .await
        .map_err(|e| {
            (
                StatusCode::BAD_GATEWAY,
                format!("Token exchange request failed: {e}"),
            )
        })?;

    if !resp.status().is_success() {
        let text = resp.text().await.unwrap_or_default();
        return Ok(Json(TokenExchangeResponse {
            success: false,
            error: Some(format!("Token endpoint returned error: {text}")),
        }));
    }

    // Parse the access_token from the response.
    // Standard OAuth token responses include at minimum `access_token` and `token_type`.
    #[derive(Deserialize)]
    struct TokenResp {
        access_token: String,
    }

    let token: TokenResp = resp.json().await.map_err(|e| {
        (
            StatusCode::BAD_GATEWAY,
            format!("Invalid token response: {e}"),
        )
    })?;

    // Update the proxy's auth header at runtime
    state
        .proxy
        .set_auth_header(Some(format!("Bearer {}", token.access_token)));

    Ok(Json(TokenExchangeResponse {
        success: true,
        error: None,
    }))
}

/// Serve the OAuth callback page (loaded in the popup).
///
/// This page extracts the authorization `code` parameter from the URL
/// and posts it to the parent window via `window.opener.postMessage`.
pub async fn callback() -> Html<&'static str> {
    Html(include_str!("../../assets/auth-callback.html"))
}

/// Return the current authentication status.
///
/// Returns `{ "authenticated": true }` when the proxy has an auth header,
/// `{ "authenticated": false }` otherwise.
pub async fn status(State(state): State<Arc<AppState>>) -> Json<serde_json::Value> {
    let has_auth = state.proxy.has_auth_header();
    Json(serde_json::json!({ "authenticated": has_auth }))
}
