//! n51 Task 2 — env-gated, authentic local `docker build` integration test for
//! the Google Cloud Run multi-crate-isolated Dockerfile.
//!
//! This proves that the Dockerfile generated by the `google-cloud-run` target's
//! public `init()` path actually `docker build`s for a multi-crate-isolated
//! layout (primary crate + one path-dep). It is the authentic counterpart to
//! the byte-match golden unit tests in
//! `src/deployment/targets/google_cloud_run/dockerfile.rs`.
//!
//! # Double-gated — never runs in normal CI (mirrors Phase 86 deploy tests)
//!
//! The real `docker build` is activated ONLY when BOTH conditions hold:
//!
//!   1. The env var `PMCP_GCR_DOCKER_TEST` is set. When it is absent the test
//!      prints a reason and `return`s — it NEVER fails the suite, so a normal
//!      `cargo test` (no Docker) stays green. The env-gate returns BEFORE any
//!      `docker` invocation, so a machine without Docker is unaffected.
//!   2. The test carries `#[ignore]`, so a bare `cargo test` does not even
//!      construct the build path (defense in depth alongside the early-return
//!      skip). It must be run with `--ignored`.
//!
//! # How to run the REAL build (operator)
//!
//! ```sh
//! # Requires: a working `docker` (with buildx) on PATH.
//! PMCP_GCR_DOCKER_TEST=1 \
//!   cargo test -p cargo-pmcp --test cloud_run_local_build -- --ignored --nocapture
//! ```

use std::path::Path;
use std::process::Command;

use cargo_pmcp::deployment::config::{DeployConfig, LayoutConfig};
use cargo_pmcp::deployment::google_cloud_run::dockerfile;

/// Env-gate. Returns `Some(reason)` when the gate is ABSENT — the test prints
/// it and `return`s WITHOUT failing. Returns `None` when the real docker-build
/// path should run.
fn docker_gate() -> Option<&'static str> {
    if std::env::var("PMCP_GCR_DOCKER_TEST").is_ok() {
        None
    } else {
        Some(
            "PMCP_GCR_DOCKER_TEST not set — skipping real local docker build \
             integration test (no Docker invoked)",
        )
    }
}

/// Synthesize a minimal multi-crate-isolated fixture under `root`:
/// a primary binary crate (`gcp-cloud-run`) that path-depends on a core lib
/// crate (`echo-core`). Each crate is a tiny hello binary/lib so the Docker
/// build is fast.
fn write_multi_crate_fixture(root: &Path) {
    // Primary binary crate.
    let primary = root.join("gcp-cloud-run");
    std::fs::create_dir_all(primary.join("src")).expect("mkdir primary/src");
    std::fs::write(
        primary.join("Cargo.toml"),
        r#"[package]
name = "gcp-cloud-run"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
echo-core = { path = "../echo-core" }
"#,
    )
    .expect("write primary Cargo.toml");
    std::fs::write(
        primary.join("src/main.rs"),
        "fn main() {\n    println!(\"{}\", echo_core::greeting());\n}\n",
    )
    .expect("write primary main.rs");

    // Path-dep lib crate.
    let core = root.join("echo-core");
    std::fs::create_dir_all(core.join("src")).expect("mkdir core/src");
    std::fs::write(
        core.join("Cargo.toml"),
        r#"[package]
name = "echo-core"
version = "0.1.0"
edition = "2021"
"#,
    )
    .expect("write core Cargo.toml");
    std::fs::write(
        core.join("src/lib.rs"),
        "#[must_use]\npub fn greeting() -> String {\n    \"hello from echo-core\".to_string()\n}\n",
    )
    .expect("write core lib.rs");
}

/// Build a `DeployConfig` for the multi-crate-isolated fixture rooted at
/// `root`, with `binary = "server"` and `primary = "gcp-cloud-run"`.
fn cloud_run_config(root: &Path) -> DeployConfig {
    let mut config = DeployConfig::default_for_cloud_run_server(
        "gcp-cloud-run".to_string(),
        "test-project".to_string(),
        "us-central1".to_string(),
        root.to_path_buf(),
    );
    config.layout = Some(LayoutConfig {
        kind: "multi-crate-isolated".to_string(),
        primary: "gcp-cloud-run".to_string(),
        path_deps: vec!["echo-core".to_string()],
    });
    config.server.binary = Some("server".to_string());
    // Use a debian base so the runtime stage works without a distroless
    // toolchain on the operator's machine (the build-correctness assertion is
    // the point, not the distroless minimisation which the unit tests cover).
    config
}

#[test]
#[ignore = "requires Docker; run with PMCP_GCR_DOCKER_TEST=1 ... -- --ignored"]
fn multi_crate_isolated_dockerfile_builds_locally() {
    if let Some(reason) = docker_gate() {
        eprintln!("SKIP: {reason}");
        return;
    }

    let tmp = tempfile::TempDir::new().expect("tmpdir");
    let root = tmp.path();
    write_multi_crate_fixture(root);

    let config = cloud_run_config(root);

    // Generate the Dockerfile via the real generator — the exact same code the
    // operator's `cargo pmcp deploy init --target-type google-cloud-run` runs
    // (and the same `render_dockerfile` the byte-match golden unit tests assert
    // against). The lib mounts this leaf so an external integration test can
    // drive it without the bin-only command layer.
    dockerfile::generate_dockerfile(&config).expect("generate Dockerfile");
    dockerfile::generate_dockerignore(&config).expect("generate .dockerignore");

    let dockerfile_path = root.join("Dockerfile");
    assert!(
        dockerfile_path.exists(),
        "generator must have written a Dockerfile"
    );

    // Real local docker build. Tag with a disposable name; we do not push.
    let image_tag = "pmcp-gcr-local-build-test:latest";
    let output = Command::new("docker")
        .current_dir(root)
        .args(["build", "-t", image_tag, "."])
        .output()
        .expect("failed to spawn `docker build` (is Docker installed and running?)");

    if !output.status.success() {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!("docker build failed:\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}");
    }

    // Best-effort cleanup of the disposable image.
    let _ = Command::new("docker")
        .args(["image", "rm", "-f", image_tag])
        .output();
}
