name = "mcp-server"
main = "worker-with-tools.js"
compatibility_date = "2024-11-05"

# Account and deployment settings
account_id = "fcff7345422986721855f13fba85be5c"
workers_dev = true               # Deploy to workers.dev subdomain
# route = "https://your-domain.com/mcp/*"  # Custom domain route

# Environment variables (if needed)
[vars]
MCP_VERSION = "2024-11-05"
SERVER_NAME = "cloudflare-worker-mcp"

# Development settings
[dev]
port = 8787
local_protocol = "http"
ip = "0.0.0.0"

# Observability
[observability]
enabled = true