name = "mcp-server-sdk"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-05"

# Account and deployment settings
account_id = "fcff7345422986721855f13fba85be5c"
workers_dev = true               # Deploy to workers.dev subdomain

# Environment variables
[vars]
MCP_VERSION = "2024-11-05"
SERVER_NAME = "cloudflare-worker-mcp-sdk"

# Build configuration for Rust/WASM
[build]
command = "cargo build --target wasm32-unknown-unknown --release --lib"

[[build.upload]]
dir = "build"
format = "modules"

[build.upload.rules]
type = "CompiledWasm"
globs = ["**/*.wasm"]

# Development settings
[dev]
port = 8787
local_protocol = "http"
ip = "0.0.0.0"

# Observability
[observability]
enabled = true