use crate::deployment::DeployConfig;
use anyhow::{Context, Result};

/// Generate the Dockerfile for an MCP server on Azure Container Apps.
///
/// This is the exact multi-stage build proven in spike 007 (a real
/// `az containerapp up --source` deploy). Notes baked in from that spike:
/// - `rust:1-slim-bookworm` builder needs `build-essential` + `pkg-config`
///   (ring/rustls need a C toolchain; slim images don't ship one).
/// - NO `cargo build --locked` unless a `Cargo.lock` is shipped — 007 hit
///   "cannot create the lock file ... --locked" and relied on a fallback.
/// - Runtime binds `$PORT` (default 8080); the server code must bind `0.0.0.0`,
///   not localhost, or Azure ingress cannot reach it.
/// - A Dockerfile MUST exist in the build context: Azure's Oryx buildpacks do
///   not support Rust, so `az containerapp up --source` only does an ACR Docker
///   build when it finds this file.
pub fn generate_dockerfile(config: &DeployConfig) -> Result<()> {
    let bin = &config.server.name;
    let dockerfile = format!(
        r#"# Multi-stage Rust build for Azure Container Apps (generated by cargo-pmcp).
# Azure Oryx buildpacks do not support Rust, so `az containerapp up --source`
# performs an ACR Docker build using this file.

FROM rust:1-slim-bookworm AS builder
WORKDIR /app
# ring/rustls need a C toolchain + pkg-config; slim images don't ship them.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config \
    && rm -rf /var/lib/apt/lists/*
COPY Cargo.toml ./
COPY src ./src
# Do NOT pass --locked unless Cargo.lock is shipped in the build context.
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -u 10001 appuser
WORKDIR /app
COPY --from=builder /app/target/release/{bin} /app/{bin}
USER appuser
# Azure Container Apps sets the published port; the server must honor $PORT and
# bind 0.0.0.0 (not 127.0.0.1) so ingress can reach it.
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["/app/{bin}"]
"#
    );

    let path = config.project_root.join("Dockerfile");
    std::fs::write(&path, dockerfile).context("Failed to write Dockerfile")?;
    println!("   ✓ Generated Dockerfile");
    Ok(())
}

/// Generate a `.dockerignore` that keeps the ACR build context small.
pub fn generate_dockerignore(config: &DeployConfig) -> Result<()> {
    let content = r#"target/
**/*.log
.DS_Store
.git/
.pmcp/
deploy/
"#;
    let path = config.project_root.join(".dockerignore");
    std::fs::write(&path, content).context("Failed to write .dockerignore")?;
    println!("   ✓ Generated .dockerignore");
    Ok(())
}
